Linear regression
grigoriizharkov/ML-sect pull request #1
Opened 2021-10-22 08:46 UTC by grigoriizharkov

2021-10-30 20:53 UTC, ARQtty requested changes
в целом очень хорошо, но надо добавить типов и сделать ООПшнее

2021-10-30 20:53 UTC, ARQtty commented on models/linear/regression.py
> +    def __init__(self, gradient, fit_intercept=True, convergence_rate=0.01, forgetting_rate=0.01, random_state=None):
тип у gradient

2021-10-30 20:53 UTC, ARQtty commented on models/linear/regression.py
> +    def _solve_accurate(self, x: np.ndarray, y: np.ndarray) -> np.ndarray:
лучше raise not implemented

2021-10-30 20:53 UTC, ARQtty commented on models/linear/regression.py
> +        if isinstance(self,
достаточно будет переопределить метод regularization в классах LinearRegression, Ridge и Lasso. Кода на проверку класса не должно быть

2021-10-30 20:53 UTC, ARQtty commented on models/linear/examples.ipynb
> +    "ax.plot(X, ridge.coef_[0] * X + ridge.coef_[1] * np.sin(X) + ridge.coef_[2], color='red', linewidth=2)\n",
ты оптимизируешь линейную множественную регрессию, а на графике рисуешь криволинейную. Небольшая подмена понятий

2021-10-31 18:32 UTC, grigoriizharkov commented on models/linear/examples.ipynb
> +    "ax.plot(X, ridge.coef_[0] * X + ridge.coef_[1] * np.sin(X) + ridge.coef_[2], color='red', linewidth=2)\n",
Согласен, не совсем справедливо. Просто хотел показать, что линейная регрессия != линейная функция (продемонстрировать возможность добавления искусственных признаков, если известен характер зависимости "признаки -> целевая переменная"). Переделал на справдливый, но не такой красивый пример

2021-11-01 11:12 UTC, ARQtty approved these changes
great

2021-11-01 11:53 UTC, merged